export const Images = {
    logo: require('./shopTesla2.png'),
    cart: require('./cart.png'),
    wallconnector: require('./wall-connector.jpeg'),
    wallconnector2: require('./wall-connector2.jpeg.jpeg'),
    wallconnector3: require('./wall-connector-charger.jpeg'),
    universalconnector: require('./universal-connector.jpeg'),
    mobileconnector: require('./mobile-connctor.jpeg'),
    nemaadaptor: require('./nema-adaptor.jpeg'),
    nemaadaptor2: require('./nema-adaptor-2.jpeg.jpeg'),
    gen2nema: require('./gen2-nema.jpeg'),
    csscombo: require('./css-combo.jpeg'),
    csscombo2: require('./css-combo2.jpeg'),
    sae177: require('./SAE 1772.jpeg'),
    mobileBag: require('./mobile-bag.jpeg'),
    teslalogo: require('./teslalogo.jpeg'),
    modal_s: require('./model-s.jpg'),
    modal_y: require('./model-y.jpg'),
    modal_x: require('./model-x.jpg'),
    modal_3: require('./model-3.jpg'),
    solar_panels: require('./solar-panel.jpg'),
    solar_roof: require('./solar-roof.jpg'),
    down_arrow: require('./down-arrow.svg'),
    accessories: require('./accessories.jpg'),
    color_faceplate: require('./color-faceplate.jpeg'),
    color_faceplate2: require('./color-faceplate2.jpeg.jpeg'),
    fastner_kit: require('./fastnerkit.jpeg'),
    wirebox_kit: require('./wirebox-kit.jpeg'),
    pedestal: require('./pedestal-connector.jpeg'),
    pedestal2: require('./pedestal-connector2.jpeg'),
    glass_faceplate: require('./glass-faceplate.jpeg'),
    glass_faceplate2: require('./glass-faceplate2.jpeg'),
    cable_organizer: require('./cable-organizer.jpeg'),
    cyberShirt: require('./cybershirt.jpeg'),
    cyberCrossbar: require('./cybertruckCrossbar.jpeg'),
    cyberquad: require('./cyberquad2.jpeg')

}